# When making changes to this file update requirements.txt also !!

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - matplotlib
  # - numpy
  - pandas
  - pip
  - requests
  - scipy
  # Not on conda channels:
  - pip:
      - mausy5043-common
      - PyNUTClient
